# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93310b53b1abe8d003ad2f0a9ef425509e04c4736238a4f0333b169a2fed5832bedf95c742646253c97720801e52bb28ca64359f7fc3168556620fb95fdd3ed

test:
  secret_key_base: 2ee141bddd7f40cb28f0d2ed88cac341c2cec4dc7753035b189fc4c18ded6ecd18a8cb6655142da8871ee33d5bdcbfc4b71bca8681783c7badeb1f344d608a40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
